### ISSUE TITLE
Different results between demo on huggingface and github repo

### ISSUE THREAD

**Issue by Oguzhanercan** [ohayonguy/PMRF#11]
Hi, thanks for your work. I cannot get good results with the repo, but I can get with your online demo.

This is the original image:

![acun-ilicali-4](https://github.com/user-attachments/assets/bb8ac9c8-d588-4a87-93e2-72c22117faac)

Here is the result of this repository. 

![Screenshot from 2024-10-15 17-39-23](https://github.com/user-attachments/assets/d724c73a-0418-486c-b79c-2b06400587e1)

For same image, the result of your web demo is:

![image](https://github.com/user-attachments/assets/0d8ca1e2-6f91-4702-9833-66bec15b5df8)

The problem could be the preprocessing step. Can you share the inference code for non-aligned face images. Or do you think that there could be another problem?

Thanks.

**Comment by ohayonguy** [comment]
I am not sure exactly how you used the code, so it's hard to say what have gone wrong. However, if you wish to try using the alignment code, you can find it here:
https://huggingface.co/spaces/ohayonguy/PMRF/blob/main/app.py
I think the input you shared is not perfectly aligned, so I expect alignment to help. But the outputs you shared seem too bizarre, so I suspect there may be another issue with how you are using the code. For example, applying this image in our demo without alignment results in:
![image](https://github.com/user-attachments/assets/a3bcd226-386c-4168-8209-abe793c34cd9)

Using alignment leads to the same result you shared:
![image](https://github.com/user-attachments/assets/c195abff-68fb-42e4-9621-21632bf77c52)

**Comment by ohayonguy** [comment]
@Oguzhanercan Please let me know how it goes!

**Comment by Oguzhanercan** [comment]
This problem solved, I got good results, thank you.

**Comment by qiuyuzhao** [comment]
> This problem solved, I got good results, thank you.


Hi, How did you solve this problem? How did you solve this problem?

**Comment by Oguzhanercan** [comment]
> > This problem solved, I got good results, thank you.
> 
> Hi, How did you solve this problem? How did you solve this problem?

Its been a long time and I cannot remember, sorry.
