### ISSUE TITLE
why My repair isn't working very well

### ISSUE THREAD

**Issue by GoingAI1998** [ohayonguy/PMRF#14]
![1730096932973](https://github.com/user-attachments/assets/634b6d9c-6342-44b4-bf42-dd204697bae7)

emmmm,Did I do something wrong ，The size of the image I entered is 512X512

**Comment by ohayonguy** [comment]
It seems that the input image you entered is too much out-of-distribution for our method (our model was not trained on images with such "blocky" artifacts). What is the original size of this input image? It seems to me that your image was originally of smaller resolution (e.g., 64x64), and you increased its resolution to 512x512 via nearest-neighbor interpolation (which creates such blockiness). I suggest that you try increasing the resolution to 512x512 via linear interpolation instead. This will create a smoother image, which our model should be able to handle.

Let me know if that helps!
