### ISSUE TITLE
PMRF: Flow from Y

### ISSUE THREAD

**Issue by eladc-git** [ohayonguy/PMRF#18]
Hi,
First of all, thank you for your great work.

I wonder if Algorithm 4 in the paper ("Flow from Y") is the optimal choice for Bline Face Restoration (BFR).
I notice that your paper only presents results of Algorithm 4 in other tasks (w.o blind degradation).
In my experiments for BFR, Algorithm 2 (condition) works much better than Algorithm 4 (I tried all kind of sigma for noise).

What can you say about single stage algorithm (2 or 4) for BFR? 

Elad

**Comment by ohayonguy** [comment]
Hi @eladc-git

Sorry, but I am not sure I properly understand all your questions. First, you wonder whether algorithm 4 would be the best option for BFR. Then, you say that you find algorithm 2 to work better than 4 in the BFR task. So why would 4 be better than all others (i.e., "optimal")? Also, if you indeed trained these algorithms on the BFR task, do you find alg.2 to work better than alg. 1 (PMRF) ? If so, could you please share the results (model checkpoint) and hyper-parameters ?

The reason we didn't train & evaluate algs. 2-4 in BFR is simple: Limited quota to use the required resources (see the last table in the appendix for the type of resources we used).
Thus, to demonstrate that PMRF is generally better than the other frameworks (algorithms 2-4), we decided to include other experiments which require less computational resources.

Regarding your last question, I believe that 4 would be slightly better than 2.
