### ISSUE TITLE
Does it support Windows

### ISSUE THREAD

**Issue by theoldsong** [ohayonguy/PMRF#3]
Deploying in Windows environment, unable to install Natten. Does this project not support Windows system? I have been unable to find the natten package under Win

**Comment by ohayonguy** [comment]
Hi @theoldsong ! Unfortunately I have not tested my code on windows. I believe you should be able to install natten, as it’s a pip package. You must be able to install natten to use the architecture we utilize (hourglass diffusion transformer (HDiT)), as this architecture uses neighborhood attention.
What is the error you are getting?

Alternatively, you could train PMRF yourself using a different architecture that does not require natten (e.g., a UNet).

**Comment by ohayonguy** [comment]
Hi @theoldsong ! Unfortunately I have not tested my code on windows. I believe you should be able to install natten, as it’s a pip package. You must be able to install natten to use the architecture we utilize (hourglass diffusion transformer (HDiT)), as this architecture uses neighborhood attention.
What is the error you are getting?

Alternatively, you could train PMRF yourself using a different architecture that does not require natten (e.g., a UNet).

Closing as this is not a particular issue with our code. Feel free to open.

**Comment by theoldsong** [comment]
> natten

Hello, pip installation cannot find the corresponding natten package for the Windows system

**Comment by ohayonguy** [comment]
@theoldsong Please check this:
https://github.com/ohayonguy/PMRF/issues/8

Let me know if it works!
