### ISSUE TITLE
Windows can't install natten?

### ISSUE THREAD

**Issue by WalkingwithAI** [ohayonguy/PMRF#4]
Hello brother, I'm unable to install NATTEN on Windows. I've tried the official installation methods, but all have failed. If it's convenient, please consider testing it on a Windows device. Thank you very much for your excellent work.

**Comment by ohayonguy** [comment]
Hey @WalkingwithAI !
Could you please try discussing this with the natten package maintainers? https://github.com/SHI-Labs/NATTEN

Maybe this is relevant? https://github.com/SHI-Labs/NATTEN/issues/147

Unfortunately I don’t possess any windows device, so I can’t really test this. Sorry.

I am closing this issue as it is not a particular issue in our code. Feel free to open.

**Comment by WalkingwithAI** [comment]
> Hey @WalkingwithAI ! 嘿！ Could you please try discussing this with the natten package maintainers? https://github.com/SHI-Labs/NATTEN您能试着和 natten 软件包维护者讨论一下吗？https://github.com/SHI-Labs/NATTEN
> 
> Maybe this is relevant? [SHI-Labs/NATTEN#147](https://github.com/SHI-Labs/NATTEN/issues/147)也许这是相关的？ [SHI-Labs/NATTEN#147](https://github.com/SHI-Labs/NATTEN/issues/147)
> 
> Unfortunately I don’t possess any windows device, so I can’t really test this. Sorry.不幸的是，我没有任何 Windows 设备，所以我无法真正测试它。不好意思。
> 
> I am closing this issue as it is not a particular issue in our code. Feel free to open.我正在关闭此问题，因为它不是我们代码中的特定问题。随意打开。

OK，Thank you my friend.
