### ISSUE TITLE
After running train_pmrf.sh, where are the model weights saved?

### ISSUE THREAD

**Issue by Yingchi1998** [ohayonguy/PMRF#7]

**Comment by ohayonguy** [comment]
Should be under the folder `wandb-project-name/wandb-run-id/`.
Let me know if you have any issue with finding it.

**Comment by Yingchi1998** [comment]
I followed the instructions, but I didn't see the folder you mentioned.
![Uploading 11.png…]()

**Comment by ohayonguy** [comment]
@Yingchi1998 I can't open the image your attached. Can you make sure it finishes uploading before commenting?

**Comment by Yingchi1998** [comment]
Sorry, I'll re-upload it.
![11](https://github.com/user-attachments/assets/b26b1452-8ac2-4d78-b5a0-0510420d2198)

**Comment by ohayonguy** [comment]
Could you please write `ls` and send a picture of the result?

**Comment by Yingchi1998** [comment]
Of course, but what do you mean by ls? I followed the instructions in section 5.1 of your readme.

**Comment by ohayonguy** [comment]
I mean printing the list of folders in linux with the command `ls`, and sending a screenshot of the outcome.

**Comment by Yingchi1998** [comment]
OK, sent it over.
![12](https://github.com/user-attachments/assets/08effb72-e2b2-461e-bb32-ac1298bd20eb)

**Comment by ohayonguy** [comment]
Sorry, not in the `wandb` folder. In the `PMRF-main` folder.

**Comment by Yingchi1998** [comment]
OK, sent it over.
![1728626408325](https://github.com/user-attachments/assets/89878db9-b970-4a2d-bac6-3fd2270d874c)

**Comment by ohayonguy** [comment]
Oh, I think I understand the issue. You have `check_val_every_n_epoch` set to 50, but you trained the algorithm only for 15 epochs. So in this case no checkpoints will be saved. You need to make sure that you train the model for at least `check_val_every_n_epoch` epochs in order for the first checkpoint to be saved.

**Comment by Yingchi1998** [comment]
Thank you for your reply. I benefited a lot from your paper. I will be grateful if you can answer my other questions.

**Comment by ohayonguy** [comment]
Happy to hear you benefited from our paper!
I am sorry, which other questions are you referring to?

**Comment by Yingchi1998** [comment]
Thank you for your reply. Why can sampling from the posterior mean ensure that the model output has the smallest distortion? What is the basis for this? Can you explain it directly?

**Comment by ohayonguy** [comment]
What do you mean by "sampling from the posterior mean"? The posterior mean is a function of the degraded input, so you can't sample from it.

Regardless, the theoretical explanation for our method is provided in section 3 in the paper. Is something there not clear?
Thanks!
