### ISSUE TITLE
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'

### ISSUE THREAD

**Issue by nitinmukesh** [ohayonguy/PMRF#9]
Hello,

Thanks for sharing your code.

I have setup on Windows 11 and using the inference.

`python inference.py --ckpt_path ./checkpoints/blind_face_restoration_pmrf.ckpt --lq_data_path testdata --output_dir results --batch_size 64 --num_flow_steps 25`

Getting the following error

```
(venv) C:\aitools\PMRF>python inference.py --ckpt_path ./checkpoints/blind_face_restoration_pmrf.ckpt --lq_data_path testdata --output_dir results --batch_size 64 --num_flow_steps 25
C:\aitools\PMRF\inference.py:24: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(args.ckpt_path, map_location="cpu")
Downloading: "https://github.com/toshas/torch-fidelity/releases/download/v0.2.0/weights-inception-2015-12-05-6726825d.pth" to C:\Users\nitin/.cache\torch\hub\checkpoints\weights-inception-2015-12-05-6726825d.pth
100%|████████████████████████████████████████████████████████████████████████████| 91.2M/91.2M [00:07<00:00, 13.3MB/s]
C:\aitools\PMRF\venv\lib\site-packages\torchmetrics\utilities\prints.py:43: UserWarning: Metric `InceptionScore` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)  # noqa: B028
Compiled model
  0%|                                                                                           | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\aitools\PMRF\inference.py", line 77, in <module>
    main(parser.parse_args())
  File "C:\aitools\PMRF\inference.py", line 47, in main
    for batch in tqdm(dl):
  File "C:\aitools\PMRF\venv\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\aitools\PMRF\venv\lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
  File "C:\aitools\PMRF\venv\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\aitools\PMRF\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'

```

Pip list 

<details>
(venv) C:\aitools\PMRF>pip list
Package                 Version
----------------------- ---------------
absl-py                 2.1.0
addict                  2.4.0
aiohappyeyeballs        2.4.3
aiohttp                 3.10.10
aiosignal               1.3.1
asttokens               2.4.1
async-timeout           4.0.3
attrs                   24.2.0
basicsr                 1.4.2
beautifulsoup4          4.12.3
certifi                 2024.8.30
charset-normalizer      3.4.0
click                   8.1.7
colorama                0.4.6
contourpy               1.3.0
cycler                  0.12.1
dctorch                 0.1.2
decorator               5.1.1
docker-pycreds          0.4.0
einops                  0.8.0
exceptiongroup          1.2.2
executing               2.1.0
fastcore                1.7.14
filelock                3.16.1
fonttools               4.54.1
frozenlist              1.4.1
fsspec                  2024.9.0
future                  1.0.0
gdown                   5.2.0
gitdb                   4.0.11
GitPython               3.1.43
grpcio                  1.66.2
huggingface-hub         0.24.5
idna                    3.10
imageio                 2.35.1
importlib_metadata      8.5.0
ipython                 8.28.0
jedi                    0.19.1
Jinja2                  3.1.4
kiwisolver              1.4.7
lazy_loader             0.4
lightning               2.3.3
lightning-utilities     0.11.7
lmdb                    1.5.1
lovely-numpy            0.2.13
lovely-tensors          0.1.16
lpips                   0.1.4
Markdown                3.7
MarkupSafe              3.0.1
matplotlib              3.9.2
matplotlib-inline       0.1.7
mpmath                  1.3.0
multidict               6.1.0
natten                  0.17.2.dev0
networkx                3.4.1
numpy                   1.26.4
nvidia-cuda-nvcc-cu11   2022.5.4
nvidia-cuda-nvcc-cu117  11.7.64
opencv-python           4.10.0.84
packaging               24.1
parso                   0.8.4
pillow                  10.4.0
pip                     22.2.1
piq                     0.8.0
platformdirs            4.3.6
prompt_toolkit          3.0.48
propcache               0.2.0
protobuf                5.28.2
psutil                  6.0.0
pure_eval               0.2.3
Pygments                2.18.0
pyparsing               3.2.0
PySocks                 1.7.1
python-dateutil         2.9.0.post0
pytorch-lightning       2.4.0
PyYAML                  6.0.2
requests                2.32.3
safetensors             0.4.5
scikit-image            0.24.0
scipy                   1.14.1
sentry-sdk              2.16.0
setproctitle            1.3.3
setuptools              63.2.0
six                     1.16.0
smmap                   5.0.1
soupsieve               2.6
stack-data              0.6.3
sympy                   1.13.3
tb-nightly              2.19.0a20241013
tensorboard-data-server 0.7.2
tifffile                2024.9.20
timm                    1.0.8
tomli                   2.0.2
torch                   2.4.1+cu124
torch-ema               0.3
torch-fidelity          0.3.0
torchaudio              2.4.1+cu124
torchmetrics            1.4.3
torchvision             0.19.1+cu124
tqdm                    4.66.5
traitlets               5.14.3
typing_extensions       4.12.2
urllib3                 2.2.3
wandb                   0.17.5
wcwidth                 0.2.13
Werkzeug                3.0.4
wheel                   0.44.0
yapf                    0.40.2
yarl                    1.15.2
zipp                    3.20.2
</details>

**Comment by ohayonguy** [comment]
I think it may be related to these issues:
1. https://discuss.pytorch.org/t/cant-pickle-local-object-dataloader-init-locals-lambda/31857
2. https://stackoverflow.com/questions/68679806/attributeerror-cant-pickle-local-object-pre-datasets-locals-lambda-when

Thus, I would try following line in `inference.py`

```
ds = ImageFolderDataset(args.lq_data_path, degradation=lambda x: (x, None), transform=to_tensor)
```
with

```
def dummy_deg(x):
    return x, None
ds = ImageFolderDataset(args.lq_data_path, degradation=dummy_deg, transform=to_tensor)
```

Unfortunately I don't have Windows so I can't reproduce your issue and confirm my suggested solution. Let me know if it worked!

**Comment by nitinmukesh** [comment]
Thank you @ohayonguy for your response. The earlier issue disappeared.

I am trying with only 1 image in testdata folder picked from WIDER-Test and got this error now

```
(venv) C:\aitools\PMRF>python inference.py --ckpt_path ./checkpoints/blind_face_restoration_pmrf.ckpt --lq_data_path testdata --output_dir results --batch_size 64 --num_flow_steps 25
C:\aitools\PMRF\inference.py:27: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(args.ckpt_path, map_location="cpu")
C:\aitools\PMRF\venv\lib\site-packages\torchmetrics\utilities\prints.py:43: UserWarning: Metric `InceptionScore` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)  # noqa: B028
Compiled model
  0%|                                                                                           | 0/1 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "C:\aitools\PMRF\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1131, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Program Files\Python310\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\aitools\PMRF\inference.py", line 80, in <module>
    main(parser.parse_args())
  File "C:\aitools\PMRF\inference.py", line 50, in main
    for batch in tqdm(dl):
  File "C:\aitools\PMRF\venv\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\aitools\PMRF\venv\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "C:\aitools\PMRF\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1327, in _next_data
    idx, data = self._get_data()
  File "C:\aitools\PMRF\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1283, in _get_data
    success, data = self._try_get_data()
  File "C:\aitools\PMRF\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1144, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 3716) exited unexpectedly

```

**Comment by ohayonguy** [comment]
I am not sure. I never encountered this issue. Maybe try to debug the code, and put a breakpoint in the data loading stage. Try to see if something goes wrong there.

Maybe also try playing with some of the data loader variables. For examples, set `pin_memory=False` or something like that.
